// components/site-header.tsx
"use client";

import * as React from "react";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowRight, Menu } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

const navLinks = [
  { label: "Services", href: "/services" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export function SiteHeader() {
  const pathname = usePathname();
  // Every link inside the sheet closes it via onClick, so no
  // route-change effect is needed.
  const [mobileOpen, setMobileOpen] = React.useState(false);

  return (
    <header className="sticky top-0 z-50 border-b border-border/60 bg-background/85 backdrop-blur-sm">
      <div className="mx-auto max-w-6xl px-6">
        <div className="flex h-16 items-center justify-between">
          {/* Logo / wordmark */}
          <Link
            href="/"
            className="flex items-center rounded-sm"
            aria-label="Kivov Digital — Home"
          >
            <Image
              src="/kivov-wordmark.png"
              alt="Kivov Digital"
              width={170}
              height={71}
              priority
              className="h-8 w-auto md:h-9"
            />
          </Link>

          {/* Desktop nav */}
          <div className="hidden items-center gap-4 md:flex">
            <NavigationMenu aria-label="Main navigation">
              <NavigationMenuList className="gap-1">
                {navLinks.map((link) => (
                  <NavigationMenuItem key={link.label}>
                    <NavigationMenuLink
                      render={<Link href={link.href} />}
                      aria-current={pathname === link.href ? "page" : undefined}
                      className={cn(
                        "px-3 py-2 font-medium",
                        pathname === link.href
                          ? "text-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                    >
                      {link.label}
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                ))}
              </NavigationMenuList>
            </NavigationMenu>
            <Button
              size="lg"
              className="rounded-xl px-5 font-semibold"
              render={<Link href="/book" />}
              aria-current={pathname === "/book" ? "page" : undefined}
            >
              Book a call
              <ArrowRight data-icon="inline-end" aria-hidden="true" />
            </Button>
          </div>

          {/* Mobile nav — shadcn Sheet */}
          <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>
            <SheetTrigger
              render={
                <Button
                  variant="ghost"
                  size="icon"
                  className="md:hidden"
                  aria-label="Toggle navigation menu"
                />
              }
            >
              <Menu aria-hidden="true" />
            </SheetTrigger>
            <SheetContent side="right" className="bg-background">
              <SheetHeader>
                <SheetTitle className="sr-only">Navigation menu</SheetTitle>
                <Image
                  src="/kivov-wordmark.png"
                  alt="Kivov Digital"
                  width={120}
                  height={50}
                  className="h-6 w-auto"
                />
              </SheetHeader>
              <nav aria-label="Mobile navigation" className="flex flex-col gap-1 px-4">
                {navLinks.map((link) => (
                  <Link
                    key={link.label}
                    href={link.href}
                    aria-current={pathname === link.href ? "page" : undefined}
                    onClick={() => setMobileOpen(false)}
                    className={cn(
                      "rounded-lg px-3 py-3 text-sm font-medium transition-colors",
                      pathname === link.href
                        ? "bg-muted text-foreground"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground",
                    )}
                  >
                    {link.label}
                  </Link>
                ))}
                <Button
                  size="xl"
                  className="mt-3 w-full"
                  render={<Link href="/book" />}
                  aria-current={pathname === "/book" ? "page" : undefined}
                  onClick={() => setMobileOpen(false)}
                >
                  Book a call
                  <ArrowRight data-icon="inline-end" aria-hidden="true" />
                </Button>
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </header>
  );
}

// components/SiteHeader.vue
<script setup lang="ts">
const route = useRoute()
const mobileOpen = ref(false)

const navLinks = [
  { label: 'Services', to: '/services' },
  { label: 'About', to: '/about' },
  { label: 'Contact', to: '/contact' },
]

// Close mobile menu on route change
watch(() => route.path, () => {
  mobileOpen.value = false
})

function toggleMobile() {
  mobileOpen.value = !mobileOpen.value
}
</script>

<template>
  <header class="border-b border-transparent bg-canvas/85 backdrop-blur-sm sticky top-0 z-50">
    <div class="max-w-6xl mx-auto px-6">
      <div class="flex items-center justify-between h-16">
        <!-- Logo / wordmark -->
        <NuxtLink
          to="/"
          class="flex items-center"
          aria-label="Kivov Digital — Home"
        >
          <img src="/kivov-wordmark.png" alt="Kivov Digital" class="h-8 md:h-9 w-auto" width="170" height="71">
        </NuxtLink>

        <!-- Desktop nav -->
        <nav aria-label="Main navigation" class="hidden md:flex items-center gap-8">
          <NuxtLink
            v-for="link in navLinks"
            :key="link.to"
            :to="link.to"
            class="nav-link"
            :class="{ 'active': route.path === link.to }"
            :aria-current="route.path === link.to ? 'page' : undefined"
          >
            {{ link.label }}
          </NuxtLink>
          <NuxtLink
            to="/book"
            class="btn-primary px-5 py-2.5 text-sm"
            :aria-current="route.path === '/book' ? 'page' : undefined"
          >
            Book a call
            <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </NuxtLink>
        </nav>

        <!-- Mobile menu button -->
        <button
          class="md:hidden p-2 rounded-md text-body hover:text-ink hover:bg-black/5 transition-colors"
          :aria-expanded="mobileOpen"
          aria-controls="mobile-menu"
          aria-label="Toggle navigation menu"
          @click="toggleMobile"
        >
          <svg v-if="!mobileOpen" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile menu -->
    <div
      v-if="mobileOpen"
      id="mobile-menu"
      class="md:hidden border-t border-line bg-canvas"
    >
      <nav aria-label="Mobile navigation" class="flex flex-col px-6 py-4 gap-1">
        <NuxtLink
          v-for="link in navLinks"
          :key="link.to"
          :to="link.to"
          class="py-3 px-3 rounded-md text-body hover:text-ink hover:bg-black/5 transition-colors text-sm font-medium"
          :class="{ 'text-ink bg-black/5': route.path === link.to }"
          :aria-current="route.path === link.to ? 'page' : undefined"
        >
          {{ link.label }}
        </NuxtLink>
        <NuxtLink
          to="/book"
          class="btn-primary mt-2 w-full"
          :aria-current="route.path === '/book' ? 'page' : undefined"
        >
          Book a call
        </NuxtLink>
      </nav>
    </div>
  </header>
</template>
