// components/SiteFooter.vue
<template>
  <footer class="border-t border-line bg-canvas">
    <div class="max-w-6xl mx-auto px-6 py-10">
      <div class="flex flex-col sm:flex-row items-center justify-between gap-6">
        <div class="flex items-center gap-4">
          <img src="/kivov-wordmark.png" alt="Kivov Digital" class="h-5 w-auto opacity-80" width="120" height="50">
          <p class="text-muted text-sm">© 2026 Kivov Digital</p>
        </div>
        <nav aria-label="Footer navigation" class="flex items-center gap-6">
          <NuxtLink
            to="/showcase"
            class="text-muted hover:text-ink transition-colors text-sm"
          >
            Showcase
          </NuxtLink>
          <NuxtLink
            to="/privacy"
            class="text-muted hover:text-ink transition-colors text-sm"
          >
            Privacy Policy
          </NuxtLink>
          <NuxtLink
            to="/cookies"
            class="text-muted hover:text-ink transition-colors text-sm"
          >
            Cookie Policy
          </NuxtLink>
          <NuxtLink
            to="/terms"
            class="text-muted hover:text-ink transition-colors text-sm"
          >
            Terms of Use
          </NuxtLink>
        </nav>
      </div>
    </div>
  </footer>
</template>

// components/site-footer.tsx
import Image from "next/image";
import Link from "next/link";

const footerLinks = [
  { label: "Showcase", href: "/showcase" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Cookie Policy", href: "/cookies" },
  { label: "Terms of Use", href: "/terms" },
];

export function SiteFooter() {
  return (
    <footer className="border-t border-border bg-background">
      <div className="mx-auto max-w-6xl px-6 py-10">
        <div className="flex flex-col items-center justify-between gap-6 sm:flex-row">
          <div className="flex items-center gap-4">
            <Image
              src="/kivov-wordmark.png"
              alt="Kivov Digital"
              width={120}
              height={50}
              className="h-5 w-auto opacity-80"
            />
            <p className="text-sm text-caption">© 2026 Kivov Digital</p>
          </div>
          <nav aria-label="Footer navigation" className="flex items-center gap-6">
            {footerLinks.map((link) => (
              <Link
                key={link.label}
                href={link.href}
                className="rounded-sm text-sm text-caption transition-colors hover:text-foreground"
              >
                {link.label}
              </Link>
            ))}
          </nav>
        </div>
      </div>
    </footer>
  );
}
