// app/(site)/book/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { Check } from "lucide-react";

import { BookingWidget } from "@/components/booking-widget";
import { Eyebrow } from "@/components/eyebrow";

export const metadata: Metadata = {
  title: "Book Your Free AI Assessment — Kivov Digital",
  description:
    "Pick a time that works — weekdays 10am–4pm ET, starting tomorrow. A free 45-minute call about how your business runs, then a written report of practical AI quick wins.",
  openGraph: {
    title: "Book Your Free AI Assessment — Kivov Digital",
    description:
      "Pick a time that works — weekdays 10am–4pm ET, starting tomorrow. A free 45-minute call about how your business runs, then a written report of practical AI quick wins.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
  },
};

const walkAway = [
  "A written report of practical AI quick wins",
  "Recommendations mapped by effort vs. impact",
  "The hours each fix gives back to your team",
  "A 30-minute walkthrough call to get you started",
];

export default function BookPage() {
  /* Wider than the standard content column so the Calendly iframe clears
     ~1000px and renders its two-column horizontal layout. */
  return (
    <div className="mx-auto max-w-6xl px-6 py-16 md:py-24">
      <div className="mb-10 max-w-3xl">
        <Eyebrow className="mb-6 text-xs">Book Your Assessment</Eyebrow>
        <h1 className="mb-4 font-display text-3xl font-semibold tracking-tight text-foreground md:text-5xl">
          Pick a time. We&apos;ll do the rest.
        </h1>
        <p className="text-lg leading-relaxed">
          45 minutes live, on Zoom, about how your business actually runs.
          Free, no card, no commitment. Within 48 hours you&apos;ll have your
          written report.
        </p>
      </div>

      <BookingWidget />

      {/* Benefits live below the scheduler, so the calendar leads. */}
      <ul className="mt-12 grid max-w-3xl gap-x-8 gap-y-3 sm:grid-cols-2">
        {walkAway.map((item) => (
          <li key={item} className="flex items-start gap-2 text-sm">
            <Check
              className="mt-0.5 size-4 shrink-0 text-primary"
              aria-hidden="true"
            />
            {item}
          </li>
        ))}
      </ul>

      <div className="mt-8 max-w-3xl">
        <p className="text-sm text-caption">
          Prefer to write a few lines first instead?{" "}
          <Link
            href="/contact"
            className="rounded-sm font-medium text-primary transition-colors hover:text-primary-hover"
          >
            Send an inquiry
          </Link>{" "}
          — we reply within one business day.
        </p>
      </div>
    </div>
  );
}

// pages/book.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Book Your Free AI Assessment — Kivov Digital',
  description: 'Pick a time that works — weekdays 10am–4pm ET, starting tomorrow. A free 45-minute call about how your business runs, then a written report of practical AI quick wins.',
  ogTitle: 'Book Your Free AI Assessment — Kivov Digital',
  ogDescription: 'Pick a time that works — weekdays 10am–4pm ET, starting tomorrow. A free 45-minute call about how your business runs, then a written report of practical AI quick wins.',
  ogType: 'website',
  twitterCard: 'summary_large_image',
})

const walkAway = [
  'A written report of practical AI quick wins',
  'Recommendations mapped by effort vs. impact',
  'The hours each fix gives back to your team',
  'A 30-minute walkthrough call to get you started',
]
</script>

<template>
  <!-- Wider than the standard .section (max-w-5xl) so the Calendly iframe
       clears ~1000px and renders its two-column horizontal layout. -->
  <div class="px-6 py-16 md:py-24 max-w-6xl mx-auto">
    <div class="max-w-3xl mb-10">
      <p class="eyebrow text-brand text-xs font-medium mb-6">
        Book Your Assessment
      </p>
      <h1 class="font-display text-3xl md:text-5xl font-semibold text-ink tracking-tight mb-4">
        Pick a time. We'll do the rest.
      </h1>
      <p class="text-body text-lg leading-relaxed">
        45 minutes live, on Zoom, about how your business actually runs. Free, no card, no commitment. Within 48 hours you'll have your written report.
      </p>
    </div>

    <BookingWidget />

    <!-- Benefits live below the scheduler now, so the calendar leads. -->
    <ul class="mt-12 grid sm:grid-cols-2 gap-x-8 gap-y-3 max-w-3xl">
      <li v-for="item in walkAway" :key="item" class="flex items-start gap-2 text-body text-sm">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-brand flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
        </svg>
        {{ item }}
      </li>
    </ul>

    <div class="mt-8 max-w-3xl">
      <p class="text-muted text-sm">
        Prefer to write a few lines first instead?
        <NuxtLink to="/contact" class="text-brand hover:text-brand-deep transition-colors font-medium">Send an inquiry</NuxtLink>
        — we reply within one business day.
      </p>
    </div>
  </div>
</template>
