// app/(site)/contact/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { Mail } from "lucide-react";

import { Card, CardContent } from "@/components/ui/card";
import { ContactForm } from "@/components/contact-form";
import { Eyebrow } from "@/components/eyebrow";

export const metadata: Metadata = {
  title: "Book a Free AI Assessment — Kivov Digital",
  description:
    "Send us a few lines — we reply within one business day. The assessment is a free 45-minute call, no card, no commitment.",
  openGraph: {
    title: "Book a Free AI Assessment — Kivov Digital",
    description:
      "Send us a few lines — we reply within one business day. The assessment is a free 45-minute call, no card, no commitment.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
  },
};

const afterYouSend = [
  {
    when: "Within 1 business day",
    what: "First reply, with a couple of proposed times for your free assessment call.",
  },
  {
    when: "The assessment call",
    what: "45 minutes on Zoom about how your business actually runs. No prep needed — you talk, we listen.",
  },
  {
    when: "Within 48 hours of the call",
    what: "Your written report: practical AI quick wins mapped by effort vs. impact, with the hours each gives back.",
  },
  {
    when: "A 30-minute walkthrough",
    what: "We go through the report together. What you do next is entirely up to you.",
  },
];

export default function ContactPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-16 md:py-24">
      <div className="grid gap-12 lg:grid-cols-5 lg:gap-16">
        {/* Left column: intro + form */}
        <div className="lg:col-span-3">
          <Eyebrow className="mb-6 tracking-widest">
            Contact · Book Your Assessment
          </Eyebrow>

          <h1 className="mb-6 font-display text-3xl font-semibold tracking-tight text-foreground md:text-4xl">
            Send us a few lines.
          </h1>

          <p className="mb-4 text-lg leading-relaxed">
            We reply within one business day. The assessment is a free
            45-minute call to understand how your business runs and where AI
            can give you time back. No card required, no commitment to go
            further.
          </p>
          <p className="mb-12 text-lg leading-relaxed">
            If we spot real opportunities, you&apos;ll have them in writing
            within 48 hours. Want to skip the back-and-forth?{" "}
            <Link
              href="/book"
              className="rounded-sm font-medium text-primary transition-colors hover:text-primary-hover"
            >
              Pick a time directly
            </Link>
            .
          </p>

          <ContactForm />
        </div>

        {/* Right column: what happens next + other ways */}
        <aside className="space-y-10 lg:col-span-2">
          <div>
            <h2 className="mb-6 text-lg font-semibold text-foreground">
              What happens after you send
            </h2>
            <ol className="space-y-5">
              {afterYouSend.map((item, i) => (
                <li key={item.when} className="flex gap-4">
                  <span
                    className="mt-0.5 shrink-0 font-mono text-sm text-primary"
                    aria-hidden="true"
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <div>
                    <p className="mb-1 text-sm font-medium text-foreground">
                      {item.when}
                    </p>
                    <p className="text-sm leading-relaxed text-muted-foreground">
                      {item.what}
                    </p>
                  </div>
                </li>
              ))}
            </ol>
          </div>

          <div>
            <h2 className="mb-4 text-lg font-semibold text-foreground">
              Other ways to reach us
            </h2>
            <Card className="ring-border [--card-spacing:--spacing(5)]">
              <CardContent>
                <div className="flex items-center gap-4">
                  <div
                    className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-secondary"
                    aria-hidden="true"
                  >
                    <Mail className="size-5 text-primary" strokeWidth={1.6} />
                  </div>
                  <div>
                    <p className="mb-0.5 font-mono text-[0.65rem] tracking-[0.2em] uppercase text-caption">
                      Email
                    </p>
                    <a
                      href="mailto:hello@kivov.work"
                      className="rounded-sm font-medium text-foreground transition-colors hover:text-primary"
                      aria-label="Send email to hello@kivov.work"
                    >
                      hello@kivov.work
                    </a>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </aside>
      </div>
    </div>
  );
}

// pages/contact.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Book a Free AI Assessment — Kivov Digital',
  description: 'Send us a few lines — we reply within one business day. The assessment is a free 45-minute call, no card, no commitment.',
  ogTitle: 'Book a Free AI Assessment — Kivov Digital',
  ogDescription: 'Send us a few lines — we reply within one business day. The assessment is a free 45-minute call, no card, no commitment.',
  ogType: 'website',
  twitterCard: 'summary_large_image',
})

const config = useRuntimeConfig()

const form = reactive({
  name: '',
  email: '',
  company: '',
  companySize: '',
  interest: '',
  message: '',
})

const status = ref<'idle' | 'sending' | 'success' | 'error'>('idle')

async function submit() {
  if (status.value === 'sending') return
  // Native validation handles this in the browser; guard for safety
  if (!form.name.trim() || !form.email.trim() || !form.message.trim()) return
  status.value = 'sending'
  try {
    const url = config.public.n8nWebhookUrl
    if (!url) throw new Error('webhook-not-configured')
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...form,
        source: 'kivov-website',
        submittedAt: new Date().toISOString(),
      }),
    })
    if (!res.ok) throw new Error(`status-${res.status}`)
    status.value = 'success'
    trackLead('contact_form')
  } catch (err) {
    console.error('Form submission failed:', err)
    status.value = 'error'
  }
}

const afterYouSend = [
  {
    when: 'Within 1 business day',
    what: 'First reply, with a couple of proposed times for your free assessment call.',
  },
  {
    when: 'The assessment call',
    what: '45 minutes on Zoom about how your business actually runs. No prep needed — you talk, we listen.',
  },
  {
    when: 'Within 48 hours of the call',
    what: 'Your written report: practical AI quick wins mapped by effort vs. impact, with the hours each gives back.',
  },
  {
    when: 'A 30-minute walkthrough',
    what: 'We go through the report together. What you do next is entirely up to you.',
  },
]
</script>

<template>
  <div class="section">
    <div class="grid lg:grid-cols-5 gap-12 lg:gap-16">
      <!-- Left column: intro + form -->
      <div class="lg:col-span-3">
        <p class="text-brand text-sm font-mono font-medium tracking-widest uppercase mb-6">
          Contact · Book Your Assessment
        </p>

        <h1 class="text-3xl md:text-4xl font-bold text-ink tracking-tight mb-6">
          Send us a few lines.
        </h1>

        <p class="text-body text-lg leading-relaxed mb-4">
          We reply within one business day. The assessment is a free 45-minute call to understand how your business runs and where AI can give you time back. No card required, no commitment to go further.
        </p>
        <p class="text-body text-lg leading-relaxed mb-12">
          If we spot real opportunities, you'll have them in writing within 48 hours. Want to skip the back-and-forth?
          <NuxtLink to="/book" class="text-brand hover:text-brand-deep transition-colors font-medium">Pick a time directly</NuxtLink>.
        </p>

        <!-- Success state -->
        <div v-if="status === 'success'" class="card border-brand/40" role="status">
          <div class="flex items-start gap-4">
            <div class="w-10 h-10 rounded-lg bg-brand/10 flex items-center justify-center flex-shrink-0" aria-hidden="true">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <div>
              <h2 class="text-ink font-semibold mb-2">Thanks — we got it.</h2>
              <p class="text-body leading-relaxed">
                You'll hear from us within one business day with a couple of proposed times for your free assessment call. Talk soon.
              </p>
            </div>
          </div>
        </div>

        <!-- Form -->
        <form v-else @submit.prevent="submit">
          <div class="space-y-6">
            <div>
              <label for="name" class="form-label">01 / Your name <span class="text-brand">*</span></label>
              <input
                id="name"
                v-model="form.name"
                type="text"
                name="name"
                required
                autocomplete="name"
                class="form-input"
                placeholder="Jane Doe"
              >
            </div>

            <div>
              <label for="email" class="form-label">02 / Work email <span class="text-brand">*</span></label>
              <input
                id="email"
                v-model="form.email"
                type="email"
                name="email"
                required
                autocomplete="email"
                class="form-input"
                placeholder="jane@yourcompany.com"
              >
            </div>

            <div>
              <label for="company" class="form-label">03 / Company</label>
              <input
                id="company"
                v-model="form.company"
                type="text"
                name="company"
                autocomplete="organization"
                class="form-input"
                placeholder="Your company name"
              >
            </div>

            <div>
              <label for="companySize" class="form-label">04 / Company size</label>
              <select id="companySize" v-model="form.companySize" name="companySize" class="form-input" :class="{ 'text-muted': !form.companySize }">
                <option value="" disabled>Select…</option>
                <option>Just me</option>
                <option>2–10</option>
                <option>11–50</option>
                <option>51–200</option>
                <option>200+</option>
              </select>
            </div>

            <div>
              <label for="interest" class="form-label">05 / What you're after</label>
              <select id="interest" v-model="form.interest" name="interest" class="form-input" :class="{ 'text-muted': !form.interest }">
                <option value="" disabled>Select…</option>
                <option>Free AI Tools Assessment</option>
                <option>AI Automation (project)</option>
                <option>Custom Software Development (project)</option>
                <option>Not sure — want to discuss</option>
              </select>
            </div>

            <div>
              <label for="message" class="form-label">06 / Tell us about your situation <span class="text-brand">*</span></label>
              <textarea
                id="message"
                v-model="form.message"
                name="message"
                required
                rows="5"
                class="form-input resize-y"
                placeholder="What does your business do, and where does your time go? A few honest lines are perfect."
              />
            </div>
          </div>

          <!-- Error state -->
          <div v-if="status === 'error'" class="mt-6 card border-red-300 bg-red-50" role="alert">
            <p class="text-body text-sm leading-relaxed">
              Hmm — something went wrong sending your message. Please email us directly at
              <a
                href="mailto:hello@kivov.work?subject=Free%20AI%20assessment"
                class="text-brand hover:text-brand-deep transition-colors font-medium"
              >hello@kivov.work</a>
              — we read everything.
            </p>
          </div>

          <div class="mt-8">
            <button type="submit" class="btn-primary" :disabled="status === 'sending'" :class="{ 'opacity-60 cursor-wait': status === 'sending' }">
              {{ status === 'sending' ? 'Sending…' : 'Book my free assessment' }}
              <svg v-if="status !== 'sending'" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </button>
            <p class="text-muted text-sm mt-4">
              First reply within 1 business day · Free, no commitment
            </p>
          </div>
        </form>
      </div>

      <!-- Right column: what happens next + other ways -->
      <aside class="lg:col-span-2 space-y-10">
        <div>
          <h2 class="text-ink font-semibold text-lg mb-6">What happens after you send</h2>
          <ol class="space-y-5">
            <li v-for="(item, i) in afterYouSend" :key="i" class="flex gap-4">
              <span class="text-brand font-mono text-sm flex-shrink-0 mt-0.5" aria-hidden="true">{{ String(i + 1).padStart(2, '0') }}</span>
              <div>
                <p class="text-ink text-sm font-medium mb-1">{{ item.when }}</p>
                <p class="text-body text-sm leading-relaxed">{{ item.what }}</p>
              </div>
            </li>
          </ol>
        </div>

        <div>
          <h2 class="text-ink font-semibold text-lg mb-4">Other ways to reach us</h2>
          <div class="card flex items-center gap-4">
            <div class="w-10 h-10 rounded-lg bg-brand/10 flex items-center justify-center flex-shrink-0" aria-hidden="true">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
              </svg>
            </div>
            <div>
              <p class="text-muted text-xs uppercase tracking-widest mb-0.5">Email</p>
              <a
                href="mailto:hello@kivov.work"
                class="text-ink font-medium hover:text-brand transition-colors"
                aria-label="Send email to hello@kivov.work"
              >
                hello@kivov.work
              </a>
            </div>
          </div>
        </div>
      </aside>
    </div>
  </div>
</template>
