// app/(standalone)/terms/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — Kivov Digital",
  description: "Terms of Use for Kivov Digital.",
  robots: { index: false },
};

export default function TermsPage() {
  return (
    <div>
      <h1 className="mb-3 font-display text-2xl font-semibold tracking-tight text-foreground md:text-3xl">
        Terms of Use
      </h1>
      <p className="mb-10 text-sm text-caption">Last updated: May 1, 2026</p>

      {/* Mirrors the Nuxt /terms page, which shows a Coming Soon notice. */}
      <div className="max-w-none">
        <p className="text-base leading-relaxed text-muted-foreground">
          <strong className="text-foreground">Coming Soon.</strong> This page
          will contain our terms of use.
        </p>
        <p className="mt-4 text-sm leading-relaxed text-caption">
          Our terms of use are currently being prepared. Please check back
          soon for the complete terms governing use of our website and
          services.
        </p>
      </div>
    </div>
  );
}

// pages/terms.vue
<script setup lang="ts">
definePageMeta({
  layout: 'standalone',
})

useSeoMeta({
  title: 'Terms of Use — Kivov Digital',
  description: 'Terms of Use for Kivov Digital.',
  robots: 'noindex',
})
</script>

<template>
  <div class="min-h-screen bg-canvas text-body">
    <div class="max-w-3xl mx-auto px-6 py-12 md:py-16">
      <!-- Minimal header for standalone / iframe use -->
      <div class="mb-10">
        <NuxtLink
          to="/"
          class="text-muted hover:text-ink transition-colors text-sm mb-8 inline-flex items-center gap-2"
          aria-label="Back to Kivov Digital homepage"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Kivov Digital
        </NuxtLink>
      </div>

      <h1 class="font-display text-2xl md:text-3xl font-semibold text-ink tracking-tight mb-3">
        Terms of Use
      </h1>
      <p class="text-muted text-sm mb-10">Last updated: May 1, 2026</p>

      <div class="prose prose-sm max-w-none">
        <p class="text-body leading-relaxed text-base">
          <strong class="text-ink">Coming Soon.</strong> This page will contain our terms of use.
        </p>
        <p class="text-muted mt-4 text-sm leading-relaxed">
          Our terms of use are currently being prepared. Please check back soon for the complete terms governing use of our website and services.
        </p>
      </div>
    </div>
  </div>
</template>
